# Generated by Django 3.2.5 on 2021-07-27 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adhar_no', models.CharField(max_length=12)),
                ('stay_type', models.CharField(choices=[('Long', 'Long_Stay'), ('Short', 'Short_Stay')], default='Short', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='HotelDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('location', models.JSONField()),
                ('amenties', models.JSONField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('description', models.TextField(max_length=300)),
                ('photo_main', models.ImageField(upload_to='description')),
                ('photo_1', models.ImageField(null=True, upload_to='description')),
                ('photo_2', models.ImageField(null=True, upload_to='description')),
                ('photo_3', models.ImageField(null=True, upload_to='description')),
                ('photo_4', models.ImageField(null=True, upload_to='description')),
                ('photo_5', models.ImageField(null=True, upload_to='description')),
            ],
        ),
        migrations.CreateModel(
            name='HotelListings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('location', models.JSONField()),
                ('pin_code', models.CharField(max_length=7)),
                ('image', models.ImageField(upload_to='image')),
            ],
        ),
    ]
