# Generated by Django 3.2.5 on 2021-08-04 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotelapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Amenties', models.JSONField()),
                ('description', models.TextField()),
                ('photo_1', models.ImageField(blank=True, upload_to='')),
                ('photo_2', models.ImageField(blank=True, upload_to='')),
                ('photo_3', models.ImageField(blank=True, upload_to='')),
                ('photo_4', models.ImageField(blank=True, upload_to='')),
                ('Hotel_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotelapi.details')),
            ],
        ),
    ]
